### ISSUE TITLE
[Migration] Migrate cairo-migrator Smart Contract from Cairo 0.10 to Cairo 1

### ISSUE THREAD

**Issue by bal7hazar** [carbonable-labs/cairo-migrator#5]
# Description

The cairo-migrator is writing in Cairo 0.10 and it is working. 

# Tasks

The Tasks are : 
- [ ] Migrate the `src/migrator` from Cairo 0.10 to Cairo 1 (preset, constants, library)
- [ ] Migrate the tests
- [ ] Add tests to migrate a Smart Contract from Cairo 0.10 to Cairo 1
